feat: adds model adaptation sample
googleapis/python-speech pull request #121
Opened 2021-03-12 02:41 UTC by b-loved-dreamer

This new sample shows how to create custom classes and phrase sets which are used for speech adaptation

2021-03-12 17:05 UTC, busunkim96 requested changes

2021-03-12 17:05 UTC, busunkim96 commented on samples/snippets/speech_model_adaptation_beta.py
> +    transcribe_with_model_adaptation(project_id, location, storage_uri)
Please move the setup for the tests into the test file and  remove the `if __name__ == "__main` block. 

For `project_id`, please fetch the project from the environment so the test can be run with different projects.

```py
import google.auth

_, project_id = google.auth.default()
```

2021-03-12 21:11 UTC, busunkim96 requested changes
I didn't notice the first time, but the test file name needs to either start with `test_` or end with `_test` for pytest to treat it as a test. It looks like it is being skipped right now.

2021-03-12 21:11 UTC, busunkim96 commented on samples/snippets/speech_model_adaptation_beta.py
> +# [END speech_transcribe_with_model_adaptation]
After the region tag please `return` the transcript so it can be checked in the test.

2021-03-12 21:11 UTC, busunkim96 commented on samples/snippets/speech_model_adaptation_test_beta.py
> +    assert "Transcript: how old is the Brooklyn Bridge" in out
```suggestion
STORAGE_URI = "gs://cloud-samples-data/speech/brooklyn_bridge.raw"
_, PROJECT_ID = google.auth.default()
LOCATION = "us-west1"

def test_model_adaptation_beta(capsys):
    transcript = speech_model_adaptation_beta.transcribe_with_model_adaptation(
        PROJECT_ID,
        LOCATION,
        STORAGE_URI
    )
    assert "Transcript: how old is the Brooklyn Bridge" in transcript
```

2021-03-12 23:35 UTC, busunkim96 reviewed
Tests are expected to setup/cleanup any resources. https://github.com/GoogleCloudPlatform/python-docs-samples/blob/89e67bcb655ed6d120dee46d2d40d866f7c72a59/storage/cloud-client/acl_test.py#L59-L65 has a good example of this.

If you need help fixing the test, please grab some time on my calendar next week.

2021-03-12 23:35 UTC, busunkim96 commented on samples/snippets/speech_model_adaptation_beta.py
> +            "custom_class_id": "seattlerestaurants",
Please make the ids for the class and phrase sets arguments to the function. That way the test can pass unique names and the tests will not clobber each other.

2021-03-12 23:35 UTC, busunkim96 commented on samples/snippets/speech_model_adaptation_beta_test.py
> +    transcript = speech_model_adaptation_beta.transcribe_with_model_adaptation(
Please add fixtures for the custom class and phrase set. Each fixture should generate a unique name with a UUID,  yield the name, and then delete the custom class and phrase set.

```py
@pytest.fixture
def custom_class_id():
    custom_class_id = f"test_custom_class_{uuid.uuid4()}"
    yield custom_class_id
    # call API method to delete this custom_class
    ...

@pytest.fixture
def phrase_set_id():
    phrase_set_id = f"test_phrase_set_{uuid.uuid4()}"
    yield phrase_set_id
    # call API method to delete this phrase set
    ...
``` 

These fixtures can than be passed through to the sample function.

This is a good example of how to incorporate a fixture into a sample test. https://github.com/GoogleCloudPlatform/python-docs-samples/blob/89e67bcb655ed6d120dee46d2d40d866f7c72a59/storage/cloud-client/acl_test.py#L59-L65

2021-03-15 16:14 UTC, busunkim96 approved these changes
Thank you for making all those changes! The tests and sample LGTM. Please delete `samples/snippets/speech_model_adaptation_test_beta.py` before merging.

2021-03-15 16:20 UTC, busunkim96 commented on samples/snippets/speech_model_adaptation_test_beta.py
> +# Copyright 2021 Google LLC
Please delete this file.

2021-03-15 16:38 UTC, telpirion approved these changes

2021-03-15 17:10 UTC, b-loved-dreamer commented on samples/snippets/speech_model_adaptation_test_beta.py
> +# Copyright 2021 Google LLC
File deleted.

2021-03-15 17:10 UTC, merged