Create example of async transcription using asyncio
googleapis/python-speech pull request #373
Opened 2022-05-19 11:26 UTC by sourabhv

2022-07-14 20:53 UTC, nicain requested changes

2022-07-14 20:53 UTC, nicain commented on samples/snippets/transcribe_async.py
> +
Do you have region tags to add here yet?

2022-07-14 22:50 UTC, yil532 commented
This sample is missing tests. :) Please kindly add corresponding test with this file.

2022-08-05 19:43 UTC, parthea commented
Hi @sourabhv,

I'm going to close this PR due to inactivity. Please re-open it when it's ready for review.

2022-08-05 19:43 UTC, closed without merging